//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Platten.Admin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Platten.Admin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Album16 {
            get {
                object obj = ResourceManager.GetObject("Album16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BSEadmin {
            get {
                object obj = ResourceManager.GetObject("BSEadmin", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue
        ///Suche.
        /// </summary>
        internal static string ButtonClearSearch_Text {
            get {
                return ResourceManager.GetString("ButtonClearSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche
        ///ausführen.
        /// </summary>
        internal static string ButtonExecuteSearch_Text {
            get {
                return ResourceManager.GetString("ButtonExecuteSearch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer
        ///Datensatz.
        /// </summary>
        internal static string ButtonNewRecord_Text {
            get {
                return ResourceManager.GetString("ButtonNewRecord_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensatz
        ///speichern.
        /// </summary>
        internal static string ButtonSaveRecord_Text {
            get {
                return ResourceManager.GetString("ButtonSaveRecord_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System
        ///Informationen.
        /// </summary>
        internal static string ButtonSystemInformations_Text {
            get {
                return ResourceManager.GetString("ButtonSystemInformations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cd {
            get {
                object obj = ResourceManager.GetObject("cd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cd_hoeren {
            get {
                object obj = ResourceManager.GetObject("cd_hoeren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cd_music {
            get {
                object obj = ResourceManager.GetObject("cd_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cdimport {
            get {
                object obj = ResourceManager.GetObject("cdimport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cdrip {
            get {
                object obj = ResourceManager.GetObject("cdrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_donut {
            get {
                object obj = ResourceManager.GetObject("chart_donut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_pie {
            get {
                object obj = ResourceManager.GetObject("chart_pie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clearsearch {
            get {
                object obj = ResourceManager.GetObject("clearsearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveFirsHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveFirsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveLastHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MovePreviousHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_NewRecordHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diskinfo {
            get {
                object obj = ResourceManager.GetObject("diskinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DRIVEDSC {
            get {
                object obj = ResourceManager.GetObject("DRIVEDSC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DRIVENET {
            get {
                object obj = ResourceManager.GetObject("DRIVENET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_UndoHS {
            get {
                object obj = ResourceManager.GetObject("Edit_UndoHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exportimage {
            get {
                object obj = ResourceManager.GetObject("exportimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_replace {
            get {
                object obj = ResourceManager.GetObject("find_replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap findfile {
            get {
                object obj = ResourceManager.GetObject("findfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disk {
            get {
                object obj = ResourceManager.GetObject("floppy_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disks {
            get {
                object obj = ResourceManager.GetObject("floppy_disks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disks1 {
            get {
                object obj = ResourceManager.GetObject("floppy_disks1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_into {
            get {
                object obj = ResourceManager.GetObject("folder_into", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_music {
            get {
                object obj = ResourceManager.GetObject("folder_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_out {
            get {
                object obj = ResourceManager.GetObject("folder_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freedb {
            get {
                object obj = ResourceManager.GetObject("freedb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gearwheel {
            get {
                object obj = ResourceManager.GetObject("gearwheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Genre16 {
            get {
                object obj = ResourceManager.GetObject("Genre16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Audio Home- Verzeichnis.
        /// </summary>
        internal static string IDS_AdminLoadMessageCheckAudiodirectory {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageCheckAudiodirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Datenbankverbindung.
        /// </summary>
        internal static string IDS_AdminLoadMessageCheckDatabaseConnection {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageCheckDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Interpreten.
        /// </summary>
        internal static string IDS_AdminLoadMessageLoadArtists {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageLoadArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Cover.
        /// </summary>
        internal static string IDS_AdminLoadMessageLoadCovers {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageLoadCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Genres.
        /// </summary>
        internal static string IDS_AdminLoadMessageLoadGenres {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageLoadGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Datenträger.
        /// </summary>
        internal static string IDS_AdminLoadMessageLoadMedia {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageLoadMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Systemeinstellungen.
        /// </summary>
        internal static string IDS_AdminLoadMessageLoadSystemSettings {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageLoadSystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Player.
        /// </summary>
        internal static string IDS_AdminLoadMessageStartPlayer {
            get {
                return ResourceManager.GetString("IDS_AdminLoadMessageStartPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentNullException {
            get {
                return ResourceManager.GetString("IDS_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgende Alben wurden geändert bzw. hinzugefügt..
        /// </summary>
        internal static string IDS_FormAdminAlbumChangedInformation {
            get {
                return ResourceManager.GetString("IDS_FormAdminAlbumChangedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler: Bitte überprüfen Sie Ihre Eingaben auf Fehler!.
        /// </summary>
        internal static string IDS_FormExceptions {
            get {
                return ResourceManager.GetString("IDS_FormExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; darf maximal {1} Zeichen enthalten!.
        /// </summary>
        internal static string IDS_FormFieldLengthException {
            get {
                return ResourceManager.GetString("IDS_FormFieldLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; darf nicht leer sein!.
        /// </summary>
        internal static string IDS_FormFieldNoNullAllowedException {
            get {
                return ResourceManager.GetString("IDS_FormFieldNoNullAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Datensatz gefunden!.
        /// </summary>
        internal static string IDS_FormFoundNoRecordInformation {
            get {
                return ResourceManager.GetString("IDS_FormFoundNoRecordInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;{0}&quot; darf nur 4-stellige Jahreszahlen enthalten! .
        /// </summary>
        internal static string IDS_FormMaskInputTxtErschDatum {
            get {
                return ResourceManager.GetString("IDS_FormMaskInputTxtErschDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie die Änderungen wirklich verwerfen?.
        /// </summary>
        internal static string IDS_FormNotSaveConfirmation {
            get {
                return ResourceManager.GetString("IDS_FormNotSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung: Ihre Änderungen sind nicht gespeichert!.
        /// </summary>
        internal static string IDS_FormNotSaveInformation {
            get {
                return ResourceManager.GetString("IDS_FormNotSaveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Datensatz wurde geändert!.
        /// </summary>
        internal static string IDS_FormRecordChangedInformation {
            get {
                return ResourceManager.GetString("IDS_FormRecordChangedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensatz {0} von {1}.
        /// </summary>
        internal static string IDS_FormRecordCountInformation {
            get {
                return ResourceManager.GetString("IDS_FormRecordCountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Änderungen wurden gespeichert!.
        /// </summary>
        internal static string IDS_FormSaveCompleteInformation {
            get {
                return ResourceManager.GetString("IDS_FormSaveCompleteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler:.
        /// </summary>
        internal static string IDS_FormSaveExceptions {
            get {
                return ResourceManager.GetString("IDS_FormSaveExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicherfehler: Bitte überprüfen Sie die Lieder auf Fehler!.
        /// </summary>
        internal static string IDS_FormSaveTracksExceptions {
            get {
                return ResourceManager.GetString("IDS_FormSaveTracksExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feld &quot;Track&quot; darf nicht leer sein und muss einen Wert grösser oder gleich 1 enthalten!.
        /// </summary>
        internal static string IDS_GrdLiederNoNullAllowedException {
            get {
                return ResourceManager.GetString("IDS_GrdLiederNoNullAllowedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen ein Passwort angeben!.
        /// </summary>
        internal static string IDS_MySqlConnectNoPasswordException {
            get {
                return ResourceManager.GetString("IDS_MySqlConnectNoPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen einen TCP/IP Port angeben!.
        /// </summary>
        internal static string IDS_MySqlConnectNoTcpIpPortException {
            get {
                return ResourceManager.GetString("IDS_MySqlConnectNoTcpIpPortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen einen Namen angeben!.
        /// </summary>
        internal static string IDS_MySqlConnectNoUserNameException {
            get {
                return ResourceManager.GetString("IDS_MySqlConnectNoUserNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Eigenschaften der Audiodisk können nur von lokalen Laufwerken angezeigt werden!.
        /// </summary>
        internal static string IDS_NetworkShareException {
            get {
                return ResourceManager.GetString("IDS_NetworkShareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string IDS_TreeViewAdministrationSystemText {
            get {
                return ResourceManager.GetString("IDS_TreeViewAdministrationSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltung.
        /// </summary>
        internal static string IDS_TreeViewAdministrationToolsText {
            get {
                return ResourceManager.GetString("IDS_TreeViewAdministrationToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InsertPictureHS {
            get {
                object obj = ResourceManager.GetObject("InsertPictureHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interpret16 {
            get {
                object obj = ResourceManager.GetObject("Interpret16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lc_save {
            get {
                object obj = ResourceManager.GetObject("lc_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifying_glass {
            get {
                object obj = ResourceManager.GetObject("magnifying_glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_beginning {
            get {
                object obj = ResourceManager.GetObject("navigate_beginning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_end {
            get {
                object obj = ResourceManager.GetObject("navigate_end", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_left {
            get {
                object obj = ResourceManager.GetObject("navigate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap navigate_right {
            get {
                object obj = ResourceManager.GetObject("navigate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap painters_palette {
            get {
                object obj = ResourceManager.GetObject("painters_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PieChart3DHS {
            get {
                object obj = ResourceManager.GetObject("PieChart3DHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PieChartHS {
            get {
                object obj = ResourceManager.GetObject("PieChartHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProtectFormHS {
            get {
                object obj = ResourceManager.GetObject("ProtectFormHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshDocViewHS {
            get {
                object obj = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap safe {
            get {
                object obj = ResourceManager.GetObject("safe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap signal_flag {
            get {
                object obj = ResourceManager.GetObject("signal_flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap signaling_disc {
            get {
                object obj = ResourceManager.GetObject("signaling_disc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap song {
            get {
                object obj = ResourceManager.GetObject("song", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tagger {
            get {
                object obj = ResourceManager.GetObject("tagger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tools_16 {
            get {
                object obj = ResourceManager.GetObject("tools_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
