//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Platten.Tunes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Platten.Tunes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Album16 {
            get {
                object obj = ResourceManager.GetObject("Album16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AutoList {
            get {
                object obj = ResourceManager.GetObject("AutoList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap broadcast {
            get {
                object obj = ResourceManager.GetObject("broadcast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BSE_16 {
            get {
                object obj = ResourceManager.GetObject("BSE_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BSEAbout {
            get {
                object obj = ResourceManager.GetObject("BSEAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BSEtunes {
            get {
                object obj = ResourceManager.GetObject("BSEtunes", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cd_hoeren {
            get {
                object obj = ResourceManager.GetObject("cd_hoeren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coverflow {
            get {
                object obj = ResourceManager.GetObject("coverflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diskinfo {
            get {
                object obj = ResourceManager.GetObject("diskinfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Filter2HS {
            get {
                object obj = ResourceManager.GetObject("Filter2HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindHS {
            get {
                object obj = ResourceManager.GetObject("FindHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder256 {
            get {
                object obj = ResourceManager.GetObject("Folder256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen256 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Genre16 {
            get {
                object obj = ResourceManager.GetObject("Genre16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften Album: {0} - {1}.
        /// </summary>
        internal static string IDS_AlbumPropertiesPanelText {
            get {
                return ResourceManager.GetString("IDS_AlbumPropertiesPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentNullException {
            get {
                return ResourceManager.GetString("IDS_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter nach Genre.
        /// </summary>
        internal static string IDS_FilterActiceFilterGenreText {
            get {
                return ResourceManager.GetString("IDS_FilterActiceFilterGenreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter nach Veröffentlichungsjahr.
        /// </summary>
        internal static string IDS_FilterActiceFilterYearText {
            get {
                return ResourceManager.GetString("IDS_FilterActiceFilterYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Lieder.
        /// </summary>
        internal static string IDS_FilterGenreColumnCountText {
            get {
                return ResourceManager.GetString("IDS_FilterGenreColumnCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string IDS_FilterGenreColumnGenreText {
            get {
                return ResourceManager.GetString("IDS_FilterGenreColumnGenreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kein Filter aktiv.
        /// </summary>
        internal static string IDS_FilterNoActiceFilterText {
            get {
                return ResourceManager.GetString("IDS_FilterNoActiceFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Lieder.
        /// </summary>
        internal static string IDS_FilterYearColumnCountText {
            get {
                return ResourceManager.GetString("IDS_FilterYearColumnCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahr.
        /// </summary>
        internal static string IDS_FilterYearColumnYearText {
            get {
                return ResourceManager.GetString("IDS_FilterYearColumnYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie Ihrer Wiedergabeliste einen Namen.
        /// </summary>
        internal static string IDS_NoPlayListNameException {
            get {
                return ResourceManager.GetString("IDS_NoPlayListNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name &quot;{0}&quot; für die Wiedergabeliste ist bereits vorhanden.
        ///Bitte wählen Sie einen anderen Namen für Ihre Wiedergabeliste aus!.
        /// </summary>
        internal static string IDS_PlayListAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("IDS_PlayListAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabeliste:.
        /// </summary>
        internal static string IDS_PlayListCaptionbarText {
            get {
                return ResourceManager.GetString("IDS_PlayListCaptionbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keine Playliste ausgewählt.
        /// </summary>
        internal static string IDS_PlayListCaptionbarTextNoPlaylistSelected {
            get {
                return ResourceManager.GetString("IDS_PlayListCaptionbarTextNoPlaylistSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim löschen:.
        /// </summary>
        internal static string IDS_PlayListDeleteException {
            get {
                return ResourceManager.GetString("IDS_PlayListDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!
        ///Soll die Wiedergabeliste &quot;{0}&quot; wirklich gelöscht werden?.
        /// </summary>
        internal static string IDS_PlayListDeleteWarningException {
            get {
                return ResourceManager.GetString("IDS_PlayListDeleteWarningException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Wiedergabeliste &quot;{0}&quot; ist leer!.
        /// </summary>
        internal static string IDS_PlayListEmptyException {
            get {
                return ResourceManager.GetString("IDS_PlayListEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim laden der Wiedergabeliste:.
        /// </summary>
        internal static string IDS_PlayListLoadException {
            get {
                return ResourceManager.GetString("IDS_PlayListLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim speichern:.
        /// </summary>
        internal static string IDS_PlayListSaveException {
            get {
                return ResourceManager.GetString("IDS_PlayListSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album:.
        /// </summary>
        internal static string IDS_StatusStripLabelPlayerTitleAlbum {
            get {
                return ResourceManager.GetString("IDS_StatusStripLabelPlayerTitleAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabeliste:.
        /// </summary>
        internal static string IDS_StatusStripLabelPlayerTitlePlaylist {
            get {
                return ResourceManager.GetString("IDS_StatusStripLabelPlayerTitlePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zufällige Wiedergabe:.
        /// </summary>
        internal static string IDS_StatusStripLabelPlayerTitleRandom {
            get {
                return ResourceManager.GetString("IDS_StatusStripLabelPlayerTitleRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied:.
        /// </summary>
        internal static string IDS_StatusStripLabelPlayerTitleSong {
            get {
                return ResourceManager.GetString("IDS_StatusStripLabelPlayerTitleSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht schliessen.
        /// </summary>
        internal static string IDS_TooltipPanelClose {
            get {
                return ResourceManager.GetString("IDS_TooltipPanelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht erweitern.
        /// </summary>
        internal static string IDS_TooltipPanelMaximize {
            get {
                return ResourceManager.GetString("IDS_TooltipPanelMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansicht reduzieren.
        /// </summary>
        internal static string IDS_TooltipPanelMinimize {
            get {
                return ResourceManager.GetString("IDS_TooltipPanelMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album: {0}.
        /// </summary>
        internal static string IDS_TrackInfoAlbum {
            get {
                return ResourceManager.GetString("IDS_TrackInfoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpret: {0}.
        /// </summary>
        internal static string IDS_TrackInfoInterpret {
            get {
                return ResourceManager.GetString("IDS_TrackInfoInterpret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lied: {0}.
        /// </summary>
        internal static string IDS_TrackInfoTrack {
            get {
                return ResourceManager.GetString("IDS_TrackInfoTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neue Wiedergabeliste erstellen.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMenuAddPlaylist {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMenuAddPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabeliste löschen.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMenuDeletePlaylist {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMenuDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMenuPlay {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zufällige Wiedergabe.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMenuPlayRandom {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMenuPlayRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meine Album Charts.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMyAlbumChartsText {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMyAlbumChartsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meine Wiedergabelisten.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMyPlaylistsText {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMyPlaylistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meine Single Charts.
        /// </summary>
        internal static string IDS_TreeViewFavoritesMySingleChartsText {
            get {
                return ResourceManager.GetString("IDS_TreeViewFavoritesMySingleChartsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Audio Home- Verzeichnis.
        /// </summary>
        internal static string IDS_TunesLoadMessageCheckAudiodirectory {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageCheckAudiodirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Datenbankverbindung.
        /// </summary>
        internal static string IDS_TunesLoadMessageCheckDatabaseConnection {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageCheckDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Datenbankhost.
        /// </summary>
        internal static string IDS_TunesLoadMessageCheckDatabaseHost {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageCheckDatabaseHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche Verlauf.
        /// </summary>
        internal static string IDS_TunesLoadMessageDeleteHistory {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageDeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Alben.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadAlbums {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Covers.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadCovers {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Favoriten.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadFavorites {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Filter.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadFilters {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Genres.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadGenres {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Verlauf.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadHistory {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Wiedergabelisten.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadPlaylists {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Systemsettings.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadSystemsettings {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadSystemsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Jahr.
        /// </summary>
        internal static string IDS_TunesLoadMessageLoadYears {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageLoadYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Player.
        /// </summary>
        internal static string IDS_TunesLoadMessageStartPlayer {
            get {
                return ResourceManager.GetString("IDS_TunesLoadMessageStartPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Interpret16 {
            get {
                object obj = ResourceManager.GetObject("Interpret16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keinBild {
            get {
                object obj = ResourceManager.GetObject("keinBild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewPlaylist16 {
            get {
                object obj = ResourceManager.GetObject("NewPlaylist16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseHS {
            get {
                object obj = ResourceManager.GetObject("PauseHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playlist1 {
            get {
                object obj = ResourceManager.GetObject("playlist1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshDocViewHS {
            get {
                object obj = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Removabledrive {
            get {
                object obj = ResourceManager.GetObject("Removabledrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveHS {
            get {
                object obj = ResourceManager.GetObject("saveHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shuffle {
            get {
                object obj = ResourceManager.GetObject("shuffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shuffle_icon {
            get {
                object obj = ResourceManager.GetObject("Shuffle_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap song {
            get {
                object obj = ResourceManager.GetObject("song", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StopHS {
            get {
                object obj = ResourceManager.GetObject("StopHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TaskHS {
            get {
                object obj = ResourceManager.GetObject("TaskHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrackInfo {
            get {
                object obj = ResourceManager.GetObject("TrackInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wiedergabe16 {
            get {
                object obj = ResourceManager.GetObject("wiedergabe16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
