//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Platten.Ripper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Platten.Ripper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gearwheel {
            get {
                object obj = ResourceManager.GetObject("gearwheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentNullException {
            get {
                return ResourceManager.GetString("IDS_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD wurde ausgeworfen.
        /// </summary>
        internal static string IDS_CDEjected {
            get {
                return ResourceManager.GetString("IDS_CDEjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD ist nicht bereit.
        /// </summary>
        internal static string IDS_CDNotReady {
            get {
                return ResourceManager.GetString("IDS_CDNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD ist bereit.
        /// </summary>
        internal static string IDS_CDReady {
            get {
                return ResourceManager.GetString("IDS_CDReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguration.
        /// </summary>
        internal static string IDS_ConfigAudioFormatFormHeader {
            get {
                return ResourceManager.GetString("IDS_ConfigAudioFormatFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD wird ausgeworfen.
        /// </summary>
        internal static string IDS_EjectCD {
            get {
                return ResourceManager.GetString("IDS_EjectCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei {0} existiert bereits
        ///Wollen Sie sie überschreiben?.
        /// </summary>
        internal static string IDS_FileToRipExistsException {
            get {
                return ResourceManager.GetString("IDS_FileToRipExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD wird geladen.
        /// </summary>
        internal static string IDS_LoadCD {
            get {
                return ResourceManager.GetString("IDS_LoadCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Kopieren wurde vom Benutzer abgebrochen!.
        /// </summary>
        internal static string IDS_RippingAbortException {
            get {
                return ResourceManager.GetString("IDS_RippingAbortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie jetzt abbrechen werden die gerippten Tracks nicht übernommen.
        ///Wollen Sie wirklich abbrechen?.
        /// </summary>
        internal static string IDS_RippingAbortInformation {
            get {
                return ResourceManager.GetString("IDS_RippingAbortInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kopiere &quot;{0}&quot; nach &quot;{1}&quot;...&quot;.
        /// </summary>
        internal static string IDS_RippingTrackInformation {
            get {
                return ResourceManager.GetString("IDS_RippingTrackInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eingabeformat muss eine Zahl sein
        ///und sie muss grösser als 0 sein!.
        /// </summary>
        internal static string IDS_TrackStartIndexEception {
            get {
                return ResourceManager.GetString("IDS_TrackStartIndexEception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream must supports seeking if AudioDataSize is not supported.
        /// </summary>
        internal static string IDS_WaveWriterArgumentException {
            get {
                return ResourceManager.GetString("IDS_WaveWriterArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap media_eject {
            get {
                object obj = ResourceManager.GetObject("media_eject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenCD {
            get {
                object obj = ResourceManager.GetObject("OpenCD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
