//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.CoverFlow.WPFLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.CoverFlow.WPFLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSEtunes.
        /// </summary>
        public static string IDS_ApplicationExceptionCaption {
            get {
                return ResourceManager.GetString("IDS_ApplicationExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} can&apos;t be null.
        /// </summary>
        public static string IDS_ArgumentException {
            get {
                return ResourceManager.GetString("IDS_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string IDS_ArtistsPanelControlHeader {
            get {
                return ResourceManager.GetString("IDS_ArtistsPanelControlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string IDS_ArtistsPanelHeader {
            get {
                return ResourceManager.GetString("IDS_ArtistsPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string IDS_DeletePlaylistDialogHeader {
            get {
                return ResourceManager.GetString("IDS_DeletePlaylistDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string IDS_HistoryExceptionCaption {
            get {
                return ResourceManager.GetString("IDS_HistoryExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string IDS_IsLoadingMessage {
            get {
                return ResourceManager.GetString("IDS_IsLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string IDS_NewPlaylistDialog_Header {
            get {
                return ResourceManager.GetString("IDS_NewPlaylistDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string IDS_NewPlaylistDialog_Lbl_PlaylistName {
            get {
                return ResourceManager.GetString("IDS_NewPlaylistDialog_Lbl_PlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entitle your playlist.
        /// </summary>
        public static string IDS_NewPlaylistDialog_NoPlayListNameException {
            get {
                return ResourceManager.GetString("IDS_NewPlaylistDialog_NoPlayListNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &quot;{0}&quot; for the playlist already exists.
        ///Please choose a different name for your playlist!.
        /// </summary>
        public static string IDS_NewPlaylistDialog_PlayListAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("IDS_NewPlaylistDialog_PlayListAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string IDS_PageCollectionHeader {
            get {
                return ResourceManager.GetString("IDS_PageCollectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickplay.
        /// </summary>
        public static string IDS_PageQuickplayHeader {
            get {
                return ResourceManager.GetString("IDS_PageQuickplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string IDS_PlayerExceptionCaption {
            get {
                return ResourceManager.GetString("IDS_PlayerExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Album.
        /// </summary>
        public static string IDS_PlayList_Header_GoToAlbum {
            get {
                return ResourceManager.GetString("IDS_PlayList_Header_GoToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Selected Tracks.
        /// </summary>
        public static string IDS_PlayList_Header_PlaySelectedTrack {
            get {
                return ResourceManager.GetString("IDS_PlayList_Header_PlaySelectedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Track.
        /// </summary>
        public static string IDS_PlayList_Header_RemoveSelectedTrack {
            get {
                return ResourceManager.GetString("IDS_PlayList_Header_RemoveSelectedTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting the playlist:.
        /// </summary>
        public static string IDS_PlayListDeleteException {
            get {
                return ResourceManager.GetString("IDS_PlayListDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you really delete the playlist &quot;{0}&quot;?.
        /// </summary>
        public static string IDS_PlayListDeleteWarningConfirmation {
            get {
                return ResourceManager.GetString("IDS_PlayListDeleteWarningConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string IDS_PlayListExceptionCaption {
            get {
                return ResourceManager.GetString("IDS_PlayListExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the playlist:.
        /// </summary>
        public static string IDS_PlayListLoadException {
            get {
                return ResourceManager.GetString("IDS_PlayListLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string IDS_TabItemHeaderPlaylists {
            get {
                return ResourceManager.GetString("IDS_TabItemHeaderPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string IDS_WidgetHistoryHeader {
            get {
                return ResourceManager.GetString("IDS_WidgetHistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string IDS_WidgetNewAlbumsHeader {
            get {
                return ResourceManager.GetString("IDS_WidgetNewAlbumsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string IDS_WindowCaptionFiltersMenuSettings {
            get {
                return ResourceManager.GetString("IDS_WindowCaptionFiltersMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string IDS_WindowCaptionFiltersMenuStatistics {
            get {
                return ResourceManager.GetString("IDS_WindowCaptionFiltersMenuStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string IDS_WindowCaptionHeaderExtras {
            get {
                return ResourceManager.GetString("IDS_WindowCaptionHeaderExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string IDS_WindowCaptionHeaderFilters {
            get {
                return ResourceManager.GetString("IDS_WindowCaptionHeaderFilters", resourceCulture);
            }
        }
    }
}
