//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Platten.BO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Platten.BO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentException {
            get {
                return ResourceManager.GetString("IDS_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!
        ///Tragen Sie bitte im Menü Extras -&gt; Optionen
        ///das Verzeichnis, in dem sie Audiodateien liegen, ein..
        /// </summary>
        internal static string IDS_ConfigurationNoAudioDirectoryException {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoAudioDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Home- Verzeichnis:.
        /// </summary>
        internal static string IDS_ConfigurationNoAudioDirectoryLabel {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoAudioDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!
        ///Tragen Sie bitte im Menü Extras -&gt; Optionen
        ///die Adresse des Datenbankservers ein..
        /// </summary>
        internal static string IDS_ConfigurationNoDataBaseException {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoDataBaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse des Datenbankservers:.
        /// </summary>
        internal static string IDS_ConfigurationNoDataBaseLabel {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoDataBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung!
        ///Tragen Sie bitte im Menü Extras -&gt; Optionen
        ///den TCP/IP Port für die Verbindung zu Ihrem Datenbankserver ein.
        ///Standard Port: {0}.
        /// </summary>
        internal static string IDS_ConfigurationNoTcpIpPortException {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoTcpIpPortException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP/IP Port des Datenbankservers:.
        /// </summary>
        internal static string IDS_ConfigurationNoTcpIpPortLabel {
            get {
                return ResourceManager.GetString("IDS_ConfigurationNoTcpIpPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Name für die Wiedergabeliste ist bereits vorhanden..
        /// </summary>
        internal static string IDS_PlaylistAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("IDS_PlaylistAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
    }
}
