//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSE.Platten.Audio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSE.Platten.Audio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        internal static string AudioPlayerToolTipMoveNext {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipMoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Züruck.
        /// </summary>
        internal static string AudioPlayerToolTipMovePrevious {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipMovePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhalten.
        /// </summary>
        internal static string AudioPlayerToolTipPause {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe.
        /// </summary>
        internal static string AudioPlayerToolTipPlay {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieder des Albums.
        /// </summary>
        internal static string AudioPlayerToolTipPlayCD {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipPlayCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string AudioPlayerToolTipStop {
            get {
                return ResourceManager.GetString("AudioPlayerToolTipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Mediaplayer hat keine Konfigurationseinstellungen.
        /// </summary>
        internal static string CMediaPlayerConfigurationControlDescription {
            get {
                return ResourceManager.GetString("CMediaPlayerConfigurationControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften MediaPlayer.
        /// </summary>
        internal static string CMediaPlayerConfigurationControlText {
            get {
                return ResourceManager.GetString("CMediaPlayerConfigurationControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Audioplayer ausgewählt.
        /// </summary>
        internal static string CNoPlayerConfigurationControlDescription {
            get {
                return ResourceManager.GetString("CNoPlayerConfigurationControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften Audioplayer.
        /// </summary>
        internal static string CNoPlayerConfigurationControlText {
            get {
                return ResourceManager.GetString("CNoPlayerConfigurationControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben keinen Audioplayer ausgewählt!.
        /// </summary>
        internal static string CPlayerManagerNoPlayerException {
            get {
                return ResourceManager.GetString("CPlayerManagerNoPlayerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unbekannter Titel.
        /// </summary>
        internal static string CPlayerUnknownTitle {
            get {
                return ResourceManager.GetString("CPlayerUnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillLeftHS {
            get {
                object obj = ResourceManager.GetObject("FillLeftHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder256 {
            get {
                object obj = ResourceManager.GetObject("Folder256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderFind {
            get {
                object obj = ResourceManager.GetObject("FolderFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen256 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoLtrHS {
            get {
                object obj = ResourceManager.GetObject("GoLtrHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} can&apos;t be null.
        /// </summary>
        internal static string IDS_ArgumentNullException {
            get {
                return ResourceManager.GetString("IDS_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; wurde nicht gefunden. Stellen Sie sicher, dass der Pfad richtig ist..
        /// </summary>
        internal static string IDS_DirectoryNotExistsException {
            get {
                return ResourceManager.GetString("IDS_DirectoryNotExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei {0} wurde nicht gefunden!.
        /// </summary>
        internal static string IDS_FileNotFoundException {
            get {
                return ResourceManager.GetString("IDS_FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Verzeichnis
        ///&quot;{0}&quot;
        ///entspricht dem Audio Home- Verzeichnis und kann deshalb nicht als Importverzeichnis verwendet werden..
        /// </summary>
        internal static string IDS_ImportDirectoryEqualsHomeDirectoryException {
            get {
                return ResourceManager.GetString("IDS_ImportDirectoryEqualsHomeDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; ist kein gültiges beschreibbares Audio Format..
        /// </summary>
        internal static string IDS_InvalidAudioFileFormatException {
            get {
                return ResourceManager.GetString("IDS_InvalidAudioFileFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ausgewählte Dateien nach {0} importieren.
        /// </summary>
        internal static string IDS_MenuCopyFileText {
            get {
                return ResourceManager.GetString("IDS_MenuCopyFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ausgewählte Dateien übernehmen.
        /// </summary>
        internal static string IDS_MenuImportFileText {
            get {
                return ResourceManager.GetString("IDS_MenuImportFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Audiodatei kann nicht übernommen werden.
        ///Bitte fügen sie der Datei
        ///&quot;{0}&quot;
        ///durch Doppelklick im Feld Track eine Tracknummer hinzu..
        /// </summary>
        internal static string IDS_NoTrackNumberException {
            get {
                return ResourceManager.GetString("IDS_NoTrackNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lese {0}.
        /// </summary>
        internal static string IDS_ReadAudioDirectoriesRead {
            get {
                return ResourceManager.GetString("IDS_ReadAudioDirectoriesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &apos;{0}&apos; kann nicht gelesen werden. Soll die Suche fortgesetzt werden?.
        /// </summary>
        internal static string IDS_ReadAudioFileException {
            get {
                return ResourceManager.GetString("IDS_ReadAudioFileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///überprüfen Sie bitte ob die Audiodateien im Moment verwendet werden..
        /// </summary>
        internal static string IDS_TaggerComExceptionExtension {
            get {
                return ResourceManager.GetString("IDS_TaggerComExceptionExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} geschrieben.
        /// </summary>
        internal static string IDS_TaggerTagWritten {
            get {
                return ResourceManager.GetString("IDS_TaggerTagWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Eingabeformat muss eine Zahl sein
        ///und sie muss grösser als 0 sein!.
        /// </summary>
        internal static string IDS_TrackStartIndexEception {
            get {
                return ResourceManager.GetString("IDS_TrackStartIndexEception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei winamp.exe kann nicht gefunden werden!
        ///Überprüfen Sie bitte die Audioplayer- Einstellungen in den Optionen..
        /// </summary>
        internal static string IDS_WinampNotFoundException {
            get {
                return ResourceManager.GetString("IDS_WinampNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie hier den Pfad zur Datei Winamp.exe an.
        ///Die Datei Winamp.exe befindet sich für gewöhnlich unter c:\programme\winamp.
        /// </summary>
        internal static string IDS_WinampPropertiesPathTo {
            get {
                return ResourceManager.GetString("IDS_WinampPropertiesPathTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschaften Winamp Player.
        /// </summary>
        internal static string IDS_WinampPropertiesTitle {
            get {
                return ResourceManager.GetString("IDS_WinampPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveNext {
            get {
                object obj = ResourceManager.GetObject("MoveNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MovePrevious {
            get {
                object obj = ResourceManager.GetObject("MovePrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OptionsHS {
            get {
                object obj = ResourceManager.GetObject("OptionsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseHS {
            get {
                object obj = ResourceManager.GetObject("PauseHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayHS {
            get {
                object obj = ResourceManager.GetObject("PlayHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Slider {
            get {
                object obj = ResourceManager.GetObject("Slider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StopHS {
            get {
                object obj = ResourceManager.GetObject("StopHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
